This is makeindex, version 2.15 [TeX Live 2011] (kpathsea + Thai support).
Scanning style file ./thesis_wing.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis_wing.acn....done (11 entries accepted, 0 rejected).
Sorting entries....done (38 comparisons).
Generating output file thesis_wing.acr....done (16 lines written, 0 warnings).
Output written in thesis_wing.acr.
Transcript written in thesis_wing.alg.
